import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import './app.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Testing App, metadata",
    template: "%s | Aakarsh"
  },
  description: "Generated by create next app",
};

interface child {
  children: ReactNode
}

export default function RootLayout({children}: Readonly<child>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/about">About</a></li>
            <li><a href="/login">Contact</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
